apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
  namespace: sample-traffic
spec:
  selector:
    app.kubernetes.io/name: echoserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
